apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    volumeMounts:
    - name: volume-known-hosts
      mountPath: /home/jenkins/.ssh        
  volumes:
  - name: volume-known-hosts
    configMap:
      name: known-hosts           