# This workflow will build and push Docker images into ghcr.io/eclipse-set
name: 'Build and push Docker image'

on: workflow_dispatch

env:
  REGISTRY: ghcr.io

jobs:
  build-push:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Login into the container registry
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Github CLI image
        uses: docker/build-push-action@94f8f8c2eec4bc3f1d78c1755580779804cb87b2 # v6.0.1
        with:
          context: .
          file: ./docker/github-cli/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/eclipse-set/github-cli:latest